server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 1000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbsys?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: true
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
logging:
  level:
    com.cj: DEBUG

